<?php

namespace Noona\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ReassortProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReassortProduitRepository extends EntityRepository
{
    public function getReassortProduitsWithReference($reassort)
    {

        $query = $this->createQueryBuilder('rp')
                ->join('rp.produit','p')
                ->addSelect('p')
                ->where('rp.reassort = :reassort')
                ->setParameter('reassort', $reassort)
                ->orderBy('p.reference','ASC')
                ->getQuery();

        return $query->getArrayResult();
    }


}
