<?php

namespace Noona\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * VenteProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteProduitRepository extends EntityRepository
{
    public function getVenteProduitsWithReference($vente)
    {

        $query = $this->createQueryBuilder('vp')
                ->join('vp.produit','p')
                ->addSelect('p')
                ->where('vp.vente = :vente')
                ->setParameter('vente', $vente)
                ->orderBy('p.reference','ASC')
                ->getQuery();

        return $query->getArrayResult();
    }


}
